[transforms.lua]
title = "Lua"
allow_you_to_description = "transform events with a full embedded [Lua][urls.lua] engine"
beta = true
common = true
function_category = "program"
input_types = ["log", "metric"]
output_types = ["log", "metric"]
requirements = {}

[transforms.lua.options.version]
type = "string"
common = true
required = true
description = """\
Transform API version. Specifying this version ensures that Vector does not \
break backward compatibility.\
"""
enum = { 2 = "Lua transform API version 2" }

[transforms.lua.options.search_dirs]
type = "[string]"
examples = [["/etc/vector/lua"]]
common = false
required = false
description = """\
A list of directories search when loading a Lua file via the `require` \
function.\
"""

[transforms.lua.options.source]
type = "string"
common = false
required = false
examples = [
"""\
custom_module = require('custom_module')\
"""
]
description = """\
The source which is evaluated when the transform is created.\
"""

[transforms.lua.options.hooks]
type = "table"
category = "Hooks"
common = true
required = true
description = "Configures hooks handlers."

[transforms.lua.options.hooks.children.init]
type = "string"
common = false
required = false
description = """\
A function which is called when the first event comes, before calling \
`hooks.process`\
"""
examples = [
"custom_module.hook_init",
"""\
function (emit)
  local f = io.popen ("/bin/hostname") -- run "hostname" command to determine the hostname
  hostname = f:read("*a") or "" -- set a global variable which can be used in other hooks
  f:close() -- close the pipe

  emit {
    log = {
      message = "initialized!"
    }
  }
end\
"""
]

[transforms.lua.options.hooks.children.process]
type = "string"
common = true
required = true
description = """\
A function which is called for each incoming event. It can produce new events \
using `emit` function.\
"""
examples = [
"""\
function (event, emit)
  event.log.field = "value" -- set value of a field
  event.log.another_field = nil -- remove field
  event.log.first, event.log.second = nil, event.log.first -- rename field
  emit(event) -- emit the processed event
end\
""",
"custom_module.hook_process"
]

[transforms.lua.options.hooks.children.shutdown]
type = "string"
common = false
required = false
description = """\
A function which is called when Vector is stopped. It can produce new events \
using `emit` function.\
"""
examples = [
"custom_module.hook_shutdown",
"""\
function (emit)
  emit {
    log = {
      message = "shutting down..."
    }
  }
end\
"""
]

[transforms.lua.options.timers]
type = "[table]"
category = "Timers"
common = false
required = false
description = """\
Configures timers which are executed periodically at given interval.\
"""

[transforms.lua.options.timers.children.interval_seconds]
type = "integer"
common = false
required = true
unit = "seconds"
description = """\
Defines the interval at which the timer handler would be executed.\
"""
examples = [1, 10, 30]

[transforms.lua.options.timers.children.handler]
type = "string"
common = false
required = true
description = """\
Defines a handler function which is executed periodially at `interval_seconds`. \
It can produce new events using `emit` function.\
"""
examples = [
"custom_module.timer_handler",
"""\
function (emit)
  emit {
    log = {
      message = "current time: " .. os.date()
    }
  }
end\
"""
]

[[transforms.lua.examples]]
label = "Add, rename, & remove log fields"
body = """\
The following examples demonstrates how to add, rename, and remove a \
[`log`][docs.data-model.log] event's fields:

```toml title="vector.toml"
# ...
hooks.process = \"\"\"
function (event, emit)
  -- Add root level field
  event.log.field = "new value"

  -- Add nested field
  event.log.nested.field = "nested value"

  -- Rename field
  event.log.new_field = event.log.old_field
  event.log.old_field = nil

  -- Remove fields
  event.log.field = nil

  emit(event)
end
\"\"\"
```\
"""

[[transforms.lua.examples]]
label = "Add, rename, & remove metric tags"
body = """\
The following examples demonstrates how to add, rename, and remove a
[`metric`][docs.data-model.log] events's tags:

```toml title="vector.toml"
# ...
hooks.process = \"\"\"
function (event, emit)
  -- Add tag
  event.metric.tags.tag = "new value"

  -- Rename tag
  event.metric.new_tag = event.log.old_tag
  event.metric.old_tag = nil

  -- Remove tag
  event.metric.tag = nil

  emit(event)
end
\"\"\"
```\
"""

[[transforms.lua.examples]]
label = "Drop event"
body = """\
Drop an event entirely. Supply this as the `hooks.process` value:

```toml title="vector.toml"
# ...
hooks.process = \"\"\"
function (event, emit)
  -- Drop event entirely by not calling the `emit` function
end
\"\"\"
```
"""
